### ISSUE TITLE
Simplify demos

### ISSUE THREAD

**Issue by jroimartin** [jroimartin/gocui#10]
For example, demo2.go has been used for testing purposes and its source code is not clear enough.

**Comment by cocodrino** [comment]
Hi..I agree with this issue...I'll appreciate if you can provide some useful samples like a menu, would be could see how you build a menu which you can select the item with the keyboard...or even better, simplify how build basic vertical/horizontal menu...inputs box and things more related to UI

thank so much..the lib seems pretty cool although I need check more the code for understand better how it works....

**Comment by jroimartin** [comment]
@cocodrino sure! I'll include more real-world examples like the ones you mentioned.

**Comment by jroimartin** [comment]
I've been working on refactoring gocui to allow building "widgets" in an easy way. The result of this refactoring is the new [Manager](https://godoc.org/github.com/jroimartin/gocui#Manager) interface.

Based on this feature, I wrote a simple example with some gadgets (labels, buttons, status bar) that can be used as a guide to build more complex ones:

[_examples/widgets.go](https://github.com/jroimartin/gocui/blob/master/_examples/widgets.go)

![screen shot 2016-10-24 at 22 36 33](https://cloud.githubusercontent.com/assets/1223476/19663053/7a4961fa-9a3a-11e6-8480-1d0ce9cb1bef.png)

Of course the implemented widgets are not "complete", but should be enough to get the idea :)

**Comment by dareg** [comment]
Thanks!
