### ISSUE TITLE
Project list - domainr

### ISSUE THREAD

**Issue by MichaelThessel** [jroimartin/gocui#101]
Hi,

Thanks for gocui! I Terminal GUI is the way forward :)

I wote [domainr](https://github.com/MichaelThessel/domainr/) which uses gocui for the UI. Feel free to add it to the projects list.

**Comment by jroimartin** [comment]
Hi! Thanks! Added via 5424b93b3bf08437980def1c4a20f6c8c362f070.

**Comment by MichaelThessel** [comment]
Thanks!
