### ISSUE TITLE
[Windows] Vertical resize only expanding view

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [jroimartin/gocui#102]
The view is not resized to a smaller size if I am descreasing the vertical axis of the terminal. Tested on windows 10 Powershell, cmd, GitCMD. Well, powershell is special because here only the enlarenment is working...

... just started to program in go using this library / tool so I am not yet ready to solve and commit this issue on my own.

**Comment by Fjolnir-Dvorak** [comment]
And silly me commited the issue to gocui without checking if wuzz just used the library in a wrong way or forgot something to implement. I am sorry.

**Comment by jroimartin** [comment]
I've just added the following example: [size](https://github.com/jroimartin/gocui/blob/master/_examples/size.go). Can you run it from the different terminals and check if the values change accordingly to the resize event?

gocui uses termbox-go under the hood, which is the package used to interact with the terminal:

https://github.com/jroimartin/gocui/blob/master/gui.go#L425

So, if it does not work, it should be reported to [termbox-go](https://github.com/nsf/termbox-go).

**Comment by jroimartin** [comment]
I'm closing the issue, as it doesn't seem to be related to gocui.
