### ISSUE TITLE
The layout is skewed on Windows

### ISSUE THREAD

**Issue by knqyf263** [jroimartin/gocui#105]
I built this sample code and ran on Windows 7.
https://github.com/jroimartin/gocui#example

The layout is skewed. How can I avoid this?

<img width="638" alt="2017-03-25 16 44 50" src="https://cloud.githubusercontent.com/assets/2253692/24320538/84f55430-117a-11e7-9e0a-94ca1e88c016.png">

Thank you for the awesome library!

**Comment by libeclipse** [comment]
Where's the sample code?

**Comment by eduncan911** [comment]
i'm not affiliated with the project, just a passer-by...

but, you'll need to supply more details.  

what shell are you using?  CMD?  trying to run from cygwin?

In the past, most of my problems for "alignment" has been the shell didn't have the correct variables set.  so, the application just had to make best guesses (120x80?  80x30?, etc).  that may have been what happened here?

try making your console Fullscreen, and run it again via command line.  most likely it is trying for something wider than your current console, and it is wrapping.

**Comment by knqyf263** [comment]
@eduncan911 Thanks for your advice!

I use `cmd.exe`.
The behavior is below.

![gocui](https://cloud.githubusercontent.com/assets/2253692/26186292/8029a5d4-3bcb-11e7-9c67-17553e35c50a.gif)

I used this sample code.
https://github.com/jroimartin/gocui#example

After try making my console fullscreen, the result is the same:cry:

![gocui_fullscreen](https://cloud.githubusercontent.com/assets/2253692/26186356/1c80a4c8-3bcc-11e7-8afe-e16a9f36fad5.gif)

**Comment by libeclipse** [comment]
I remember someone mentioning this exact issue before, but I can't seem to find it. What version are you using?

**Comment by knqyf263** [comment]
I'm using the latest version of `gocui`. 
I did `go get github.com/jroimartin/gocui` a while ago.

The latest commit is `612b0b2987ec1a6af46d7008cef1efd4b3898346`

I cross-compiled on Mac. Is it affected?
```
$ go version
go version go1.7.5 darwin/amd64
$ GOOS=windows GOARCH=386 go build
```

**Comment by libeclipse** [comment]
Shouldn't be. Cross compiling in Go should be the same as compiling on the
target platform.

**Comment by jroimartin** [comment]
Can you try setting `g.ASCII = True`?

https://github.com/jroimartin/gocui/blob/master/gui.go#L66-L68

Related: #93, #91

**Comment by jroimartin** [comment]
I'm closing the issue for now. I think it duplicates the issues linked in my last comment. It that's not the case, feel free to reopen it :)
