### ISSUE TITLE
Mouse clicks are not triggering correct key bindings for overlapping views

### ISSUE THREAD

**Issue by telecoda** [jroimartin/gocui#107]
I have noticed that mouse events are not triggering keybindings if there is a larger view in front of a smaller view.  Even when the smaller view is set to be the TOP view.

This is because the views are being checked from the bottom upwards, not top down.

The PR below fixes the issue.
https://github.com/jroimartin/gocui/pull/106

**Comment by jroimartin** [comment]
Thanks for the fix! The PR has been merged, so I'm closing this issue.
