### ISSUE TITLE
What is the difference between Buffer() and ViewBuffer()?

### ISSUE THREAD

**Issue by pkazmier** [jroimartin/gocui#110]
I'm trying to understand the difference between `Buffer()` and `ViewBuffer()`. My understanding is that `ViewBuffer()` should only return what is actually viewable on the screen. However, this is not the behavior seen when running the `_examples/buf.go` demo. It also does not work with the `_examples/demo.go` when pressing `KeyCtrlW`, which saves the entire text of Tom Sawyer. Am I missing something obvious? Thanks!

**Comment by thehowl** [comment]
From what I understood, the difference is mostly useful when Wrap is true. In that case, ViewBuffer returns the buffer with newlines as they are shown on screen, while Buffer has newlines only when there are actually in the text.

If you need to calculate the position of the Cursor/Origin, you should use ViewBuffer. If you need to get the contents of a view to handle the text, use Buffer.

**Comment by jroimartin** [comment]
Exactly. Long story short, what you see in the screen is a slice of `ViewBuffer()`.

<img width="169" alt="screen shot 2017-08-15 at 21 46 18" src="https://user-images.githubusercontent.com/1223476/29333208-38e6769c-8203-11e7-8806-216db1568850.png">

<img width="219" alt="screen shot 2017-08-15 at 21 46 30" src="https://user-images.githubusercontent.com/1223476/29333215-3baae78c-8203-11e7-9864-7ea806f1842d.png">
