### ISSUE TITLE
Shift-Enter?

### ISSUE THREAD

**Issue by thehowl** [jroimartin/gocui#111]
How can I handle the case where the user presses Shift-Enter? I want to use this in case in my textfield the user wants to force a newline instead of a send, but I see that there is no documented way for handling Shift + Enter.

This also holds true even for some Ctrl combinations, like Ctrl-Left and Ctrl-Right

**Comment by whereswaldon** [comment]
I expect that it isn't implemented in `termbox-go` because it can't be represented portably across all of the platforms that Go supports. If that is the case, it cannot be implemented.

**Comment by miguelmota** [comment]
termbox-go maintainer has no plans of implementing Shift+Enter for the reason stated above, in that it must be supported by all terminals 

https://github.com/nsf/termbox-go/issues/204
