### ISSUE TITLE
make count of lines public

### ISSUE THREAD

**Issue by alitari** [jroimartin/gocui#117]
view.go
...
func (v *View) LinesCount() int {
	return len(v.lines)
}

**Comment by jroimartin** [comment]
What about using `strings.Count(v.ViewBuffer(), "\n")` or `strings.Count(v.Buffer(), "\n")` depending on your needs?

Related: #84

**Comment by alitari** [comment]
Thanks for your fast reply and btw: good work !
In fact, that's what I'm doing right now, but imho calculating a value which is already there ( just hidden) is not optimal. Anyway i can live with this workaround of course :-)

**Comment by jroimartin** [comment]
The thing is that there are actually multiple line counts: number of lines in the internal viewbuffer, number of lines in the internal buffer, maximum number of lines of the view (y size), etc.

So, I'm not sure if exposing all of them would make the API harder to understand, given that there are already other ways to get them.
