### ISSUE TITLE
Cannot update view via Gui.Update

### ISSUE THREAD

**Issue by nboughton** [jroimartin/gocui#123]
I have followed the examples and have tested my input (server connection streaming back text data via telnet). I am certain that I am receiving data but for some reason the main view appears blank. If I append +"#" to str in the fmt.Fprint(v, str) line I can see '#'s show up in the window but text from the server never appears. 

The updating goroutine is as follows:

	go func() {
		b := bufio.NewReader(conn)
		for {
			mu.Lock()
			str, _ := b.ReadString('\n')
			mu.Unlock()

			gui.Update(func(g *gocui.Gui) error {
				v, err := g.View(vMain)
				if err != nil {
					return err
				}

				fmt.Fprint(v, str)
				//v.Write([]byte(str))
				//fmt.Print(str)
				return nil
			})
		}
	}()

This is run after establishing a connection to the server, and setting the layout and keybindings, but before running the g.MainLoop()

If I put a fmt.Print(str) in there I can see the correct data coming back from the server printing directly to standard out but nothing I do seems to get the View to update. The View in question is set up in the layout function as follows:

	if v, err := g.SetView(vMain, int(0.2*float32(maxX)), 0, maxX, maxY); err != nil {
		if err != gocui.ErrUnknownView {
			return err
		}

		// Set some view paramters
		v.Title = "Main"
		v.Autoscroll = true
		v.Wrap = true
	}

Have I missed something?

**Comment by jroimartin** [comment]
Without the real code it's difficult to say. Anyway, I created an small example that might be useful for you. It basically reads from a socket and outputs the received data in a view:

https://gist.github.com/jroimartin/bd64b6c88c8289e80b01f2119716e64e

![image](https://user-images.githubusercontent.com/1223476/29945406-4b696c48-8ea1-11e7-9ea2-e076940ecaaf.png)

**Comment by nboughton** [comment]
I've pushed my current code to a repo: https://github.com/nboughton/go-disc

The problem seems to be in printing to the main view, the receiver routine is in recv.go

**Comment by nboughton** [comment]
Ah, interestingly I can get the raw output printing if I use fmt.Fprintf(v, "%q\n", str), however this also prints all the color codes and return bytes.

**Comment by nboughton** [comment]
OK!, I've fixed it in the current version of the code. It appears that it works if I use b.Readline() to receive the string data from the server and then Fprintf that out to the view.

Thanks!
