### ISSUE TITLE
stdin example

### ISSUE THREAD

**Issue by engineerbeard** [jroimartin/gocui#125]
Doing a go build on stdin.go in the examples folder and then a ./stdin causes the program to hang on  MAC El Capitan 10.11.6.

**Comment by jroimartin** [comment]
It hangs because it's waiting for stdin data. Try something like this:

```
$ cat /bin/ls | go run _examples/stdin.go
```

**Comment by engineerbeard** [comment]
That worked, I figured it was waiting for keyboard stdin.
