### ISSUE TITLE
Add one or two screenshots to the README.md

### ISSUE THREAD

**Issue by kelseyhightower** [jroimartin/gocui#14]
This looks like an awesome tool, but since it involves UI, a screenshot of a console showing off gocui would be nice.

**Comment by jroimartin** [comment]
![examples_demo](https://cloud.githubusercontent.com/assets/1223476/5992750/720b84f0-aa36-11e4-88ec-296fa3247b52.png)
![examples_delete](https://cloud.githubusercontent.com/assets/1223476/5992751/76ad5cc2-aa36-11e4-8204-6a90269db827.png)
