### ISSUE TITLE
tainted views

### ISSUE THREAD

**Issue by jezek** [jroimartin/gocui#140]
Sorry for bothering you ...
I was browsing through your code and I realized, you mark views as tainted on some occasions, but there is nowhere a condition to check if some view is tainted. [See search.](https://github.com/jroimartin/gocui/search?utf8=%E2%9C%93&q=tainted&type=) So you always redraw all border all the time? Or have I overlooked something?

Thank you for your time and have a nice day ... always ;)

**Comment by evilgroot** [comment]
Hi there! Maybe I'm a little late but anyway...

Have a look at this:
https://github.com/jroimartin/gocui/blob/c055c87ae801372cd74a0839b972db4f7697ae5f/view.go#L297

When a View is marked as tainted, its ViewBuffer needs to be computed again (this is the viewLines slice).

**Comment by jezek** [comment]
Ahaaa ... so I trusted GitHub search too much ... it doesn't show all results.
My fault. Sorry.
Consider this not a bug.
