### ISSUE TITLE
Weird look on iTerm vs Terminal on macOS

### ISSUE THREAD

**Issue by AlexLombry** [jroimartin/gocui#202]
**Describe the bug**
Weird look on iTerm2 vs Terminal

I'm still tweaking my configuration but i always have that kind of behaviour.
I'm running oh my zsh on both iterm and terminal.

**Screenshots**
__macOS Built in terminal__
![Terminal](https://imgshare.io/images/2019/07/02/terminal.png)

__iTerm2__
![iTerm2](https://imgshare.io/images/2019/07/02/iterm.png)

**Desktop :**
 - OS: macOS High Sierra 

__I have this problem with multiple application created with GoCUI__

**Comment by ghostsquad** [comment]
Any update on this? Is this still a problem?

**Comment by AlexLombry** [comment]
This problem occurs with certains types of Font.
I don't have the problem anymore.

**Comment by ghostsquad** [comment]
What types of fonts should I stay away from?

**Comment by AlexLombry** [comment]
I cannot reproduce this bug so maybe it was fix on gocui side

**Comment by ghostsquad** [comment]
thanks for the update! 😄
