### ISSUE TITLE
Fix the Chinese display issue, but still got wrong ui layout

### ISSUE THREAD

**Issue by aaronchen2k** [jroimartin/gocui#208]
I fixed the Chinese issue by using codes in https://github.com/rocket049/gocui.
But still have layout bug.

![image](https://user-images.githubusercontent.com/3222874/65824432-ab1b1d80-e29b-11e9-80e4-20fc3f93f292.png)

**Comment by mjarkk** [comment]
Have you looked at this fork: [awesome-gocui/gocui](https://github.com/awesome-gocui/gocui), it's a community fork that also has a number of fixes related to this.  
The owner of this library seems to be stopped working on it so we made a fork with a lot of community fixes and other improvements.

**Comment by aaronchen2k** [comment]
@mjarkk It works well, thanks a lot!
