### ISSUE TITLE
Keybindings not working on FreeBSD

### ISSUE THREAD

**Issue by miguelmota** [jroimartin/gocui#214]
I run the examples but pressing any of the keybindings doesn't have any effect. It doesn't let me quit either. I tested on a fresh install of FreeBSD using latest Go. Any idea?

**Comment by mjarkk** [comment]
We have a similar issue, https://github.com/jesseduffield/lazygit/issues/563  
It seems like this only happens in the latest versions of go.

**Comment by miguelmota** [comment]
@mjarkk are you sure it's a go version issue? keybindings using the [tcell](https://github.com/gdamore/tcell) library seem to work

**Comment by miguelmota** [comment]
gocui relies on termbox-go for keybindings. A fix just got [merged](https://github.com/nsf/termbox-go/pull/219/files) on termbox-go which fixes keybindings on freebsd. Closing issue since it's resolved.
