### ISSUE TITLE
Add a project that using gocui

### ISSUE THREAD

**Issue by saeeddhqan** [jroimartin/gocui#224]
[evine](https://github.com/saeeddhqan/evine)

Evine is a simple, fast, and interactive web crawler and web scraper written in Golang. Evine is useful for a wide range of purposes such as metadata and data extraction, data mining, reconnaissance, and testing.

**Comment by raphaelauv** [comment]
This REPO is dead, things are happening there ->

https://github.com/awesome-gocui/gocui
