### ISSUE TITLE
lazygit is a simple terminal UI for git commands, written in Go with the gocui library.

### ISSUE THREAD

**Issue by Yanwenjiepy** [jroimartin/gocui#231]
[lazygit](https://github.com/jesseduffield/lazygit) is a simple terminal UI for git commands, written in Go with the gocui library.

**Comment by mjarkk** [comment]
This was also already mentioned in https://github.com/jroimartin/gocui/issues/132

**Comment by Yanwenjiepy** [comment]
> 这在[#132中](https://github.com/jroimartin/gocui/issues/132)也已经提到[](https://github.com/jroimartin/gocui/issues/132)

ok
