### ISSUE TITLE
Better tags support

### ISSUE THREAD

**Issue by AndzheyAsryan** [jroimartin/gocui#236]
`T` add a tag to the commit, but I couldn't find a hotkey to delete one. Nor there's a way to push tags to the origin.

**Comment by mjarkk** [comment]
Euuu I have some suspicion this issue was meant for [lazygit](https://github.com/jesseduffield/lazygit) not gocui

**Comment by AndzheyAsryan** [comment]
Oh man, my bad, need to focus...
