### ISSUE TITLE
Lazydocker is not listed

### ISSUE THREAD

**Issue by SAVE-POlNT** [jroimartin/gocui#240]
I saw that lazy docker is not listed here so i wanted to let you kniw that one of the best projects im using is using this repo

https://github.com/jesseduffield/lazydocker

also pls let me know if this is still maintained , i plan to use it form my "lazyvenv" project

**Comment by jwlodek** [comment]
It is unmaintained, there is a more recently maintained fork: https://github.com/awesome-gocui/gocui

**Comment by SAVE-POlNT** [comment]
ok thank you i will take a look at this fork
