### ISSUE TITLE
SetKeyBinding fails when called via a helper function

### ISSUE THREAD

**Issue by stephenwithav** [jroimartin/gocui#29]
When defining my keybindings, I use this helper function:

    func setkey(g *gocui.Gui, key gocui.Key, fn gocui.KeybindingHandler) {
	    if err := g.SetKeybinding("", key, gocui.ModNone, fn); err != nil {
		    log.Panicln(err)
	    }
    }

An example invocation that works is:

    setKey(g, gocui.KeyCtrlC, quit)

...but the following fails:

    setKey(g, 'q', quit)

...while the following correctly binds the `q` key:

	    if err := g.SetKeybinding("", 'q', gocui.ModNone, quit); err != nil {
		    log.Panicln(err)
	    }

I'm pretty sure I'm missing something obvious here.

**Comment by jroimartin** [comment]
The signature of your helper function should be:

```go
func setkey(g *gocui.Gui, key interface{}, fn gocui.KeybindingHandler)
```

Because key can be a gocui.Key or a rune. Try and let me know if it works ok for you :)

**Comment by stephenwithav** [comment]
Fantastic!  Thank you, @jroimartin !
