### ISSUE TITLE
view titles

### ISSUE THREAD

**Issue by dcu** [jroimartin/gocui#30]
hi,

is there a way to add a title to the view? 
If not, that'd be nice to have, it can be in the same level as the frame like https://github.com/gizak/termui does.

The syntax could be something like this:

	if v, err := g.SetView(...); err != nil {
		v.Title = "Title"
		v.TitleAlign = "left|right|center"
	}

**Comment by jroimartin** [comment]
I'd prefer to keep views as simple as possible, think on them just as buffers. In the case of needing a title, I would add another view above just with the title (one line height, you can disable borders, etc.)

**Comment by jroimartin** [comment]
I've implemented this feature based on the PR #36 from @conejoninja. You can check it on branch [view-title](https://github.com/jroimartin/gocui/tree/view-title) commit bb01d13a959295e85f4eb6b4bf0cfdec6526252d. The main difference between my patch and the original PR is that I iterate over the title string, avoiding unnecessary iteration during the draw loop. 

I also added an example with all the use cases under [_examples/title.go](https://github.com/jroimartin/gocui/blob/bb01d13a959295e85f4eb6b4bf0cfdec6526252d/_examples/title.go) to test long titles, overlap between views, small views with title, etc.

Could you please check if it works as expected? :)

**Comment by jroimartin** [comment]
This is the output of *_examples/title.go*:

![image](https://cloud.githubusercontent.com/assets/1223476/12867126/839c53fc-cce5-11e5-9251-b24f6e6b3d3a.png)

**Comment by conejoninja** [comment]
Looks good to  me, no problems so far

**Comment by jroimartin** [comment]
Great. I've just merged it!
