### ISSUE TITLE
Add a View method that returns the actual contents of the view

### ISSUE THREAD

**Issue by urandom** [jroimartin/gocui#31]
Currently, if a view is wrapped, there seems to be no way to actually return the new view content, including the extra newlines. Buffer returns the content before the newlines have been calculated. This makes implementing scrolling with boundaries impossible.

**Comment by jroimartin** [comment]
First of all, sorry for the late response. Take a look at e5bf60e36b67610cf66ef779ad2b83c317b5ec49, I added the method View.ViewBuffer() that returns the contents of the buffer that is showed to the user.
