### ISSUE TITLE
Cursor Not Displaying 

### ISSUE THREAD

**Issue by shibukraj** [jroimartin/gocui#40]
Hi jroimartin,
Thanks for answering my earlier question. I am asking this question as a new thread, thinking that others who want to use this fantastic library may find these Q&A helpful.

The issue/question I am having is, I have to draw a UI and ask for the user input. I would like to show the cursor in the screen (may be blinking as well) so user knows where the cursor is. I created a sample using gocui https://github.com/shibukraj/synapseconsole/blob/master/console-dev.go

While running I am not able to draw the cursor at all. Can you guide me please.

Thanks again

**Comment by shibukraj** [comment]
I got the issue figured out. Thanks

**Comment by jroimartin** [comment]
Cool! :)

**Comment by AnirudhVyas** [comment]
how? running into same issue ...

**Comment by Rudi9719** [comment]
Also having this issue; necro from 2017 but it's 2019 and this shows up first in Google. How did you get the cursor to show up?
