### ISSUE TITLE
Can I use gocui with a pty which behind a ssh server?

### ISSUE THREAD

**Issue by jack230230** [jroimartin/gocui#42]
I have an idea about create an interactive session bebind a ssh server.

thus I want to get a interactive console interface build by gocui, so I want to know how to build gocui with a pty.

**Comment by jack230230** [comment]
here is a picture which show my idea

![image](https://cloud.githubusercontent.com/assets/1728779/13344921/6df5b556-dc95-11e5-9134-494e4e118518.png)

**Comment by jroimartin** [comment]
Actually this is a question related to termbox-go (used by gocui under the hood). I'm closing this issue because I've seen you already asked nsf at https://github.com/nsf/termbox-go/issues/123.
