### ISSUE TITLE
View based on Struct ?

### ISSUE THREAD

**Issue by matrixise** [jroimartin/gocui#43]
Hi,

How to define a View over a collection of structs ?

An idea? 

Thank you

**Comment by jroimartin** [comment]
To be honest, I don't get your question. Could you provide an example?

**Comment by matrixise** [comment]
hi @jroimartin 

in fact, when you show a text line on the console, it's just a string, not a struct. what do you suggest if you want to implement a Model-View-Controller with your library ?

**Comment by jroimartin** [comment]
> in fact, when you show a text line on the console, it's just a string, not a struct.

Yes, it would be a string. Why would you want it to be an struct? What do you want to accomplish?

**Comment by jroimartin** [comment]
Closed due to inactivity.
