### ISSUE TITLE
can't read from stdin

### ISSUE THREAD

**Issue by andrewwatson** [jroimartin/gocui#46]
The _examples/stdin.go won't run for me on os/x in go 1.5 or 1.6.  The program just hangs and when you kill it from another terminal it outputs this

```
2016/04/01 00:27:04 read /dev/stdin: input/output error
```

Could it be a problem with the way it's reading from stdin maybe interfering with the keybindings?

**Comment by jroimartin** [comment]
It's working for me. The command:

`$ echo This is a test | go run stdin.go`

returns:

![image](https://cloud.githubusercontent.com/assets/1223476/14761371/72141d02-095f-11e6-829b-92051d0d35dd.png)
