### ISSUE TITLE
unicode friendly

### ISSUE THREAD

**Issue by mattn** [jroimartin/gocui#49]
The border characters are not good for windows. You expect `│` or `┐` are single width character. but it's ambiguous width characters in unicode. They are displayed as double width characters in east asia. http://www.unicode.org/reports/tr11/

And also, I'm looking _example/demo.go, it seems not support multi-byte characters. for example, when typing `あ`, it should move the cursor forwarding two cells.

**Comment by jroimartin** [comment]
When I started coding gocui I decided to support only 1 cell-width runes, which is the most common case. But, of course, PRs are more than welcome :)

If you decide to implement it, please take into account that you will need to modify: edition mode rutines, horizontal scrolling, view drawing, geometric calculations to map visual buffers to content buffers, etc.
