### ISSUE TITLE
The function Line() and line highlighting should take the Wrap flag into consideration.

### ISSUE THREAD

**Issue by pengux** [jroimartin/gocui#50]
Currently, when the Wrap flag is set to true for a view, the Line() method doesn't return the whole line, but only the part that fit in one row. The same problem exists for line highlighting as it only highlight the part on the same row instead of the whole wrapped line.

**Comment by jroimartin** [comment]
Highlight should be fixed with 0707386452711db7b0d58fff7e13dd2f28e1db3e. Regarding the Line() method, it works fine here. Could you check, please?
