### ISSUE TITLE
Support \r when printing

### ISSUE THREAD

**Issue by jantb** [jroimartin/gocui#51]
When printing to view
`fmt.Fprint(v, "\r test")` 

casts:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x80 pc=0x4e1e95]

goroutine 1 [running]:
panic(0x7ca780, 0xc82000e1a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/jroimartin/gocui.(*View).Write(0x0, 0xc820263c40, 0x6, 0x8, 0x720000, 0x0, 0x0)
	/home/janbo/src/github.com/jroimartin/gocui/view.go:197 +0x45
fmt.Fprint(0x7f5a542ad1c8, 0x0, 0xc82004ba50, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:223 +0xa5

**Comment by jroimartin** [comment]
Cannot reproduce the issue with the following code. Are you using master? Can you give some more context?

Thanks!

```go
package main

import (
	"fmt"
	"log"

	"github.com/jroimartin/gocui"
)

func main() {
	g := gocui.NewGui()
	if err := g.Init(); err != nil {
		log.Panicln(err)
	}
	defer g.Close()

	g.SetLayout(layout)

	if err := g.SetKeybinding("", gocui.KeyCtrlC, gocui.ModNone, quit); err != nil {
		log.Panicln(err)
	}

	if err := g.MainLoop(); err != nil && err != gocui.ErrQuit {
		log.Panicln(err)
	}
}

func layout(g *gocui.Gui) error {
	maxX, maxY := g.Size()
	if v, err := g.SetView("hello", maxX/2-7, maxY/2, maxX/2+7, maxY/2+2); err != nil {
		if err != gocui.ErrUnknownView {
			return err
		}
		fmt.Fprint(v, "\r test")
	}
	return nil
}

func quit(g *gocui.Gui, v *gocui.View) error {
	return gocui.ErrQuit
}
```

**Comment by jroimartin** [comment]
Also, make sure in your code `v` is not nil, because, based on the backtrace, the error is in view.go:197:

```go
        v.tainted = true
```

**Comment by jroimartin** [comment]
Mark as invalid. Feel free to re-open it if the bug is in gocui.

**Comment by mkchoi212** [comment]
@jroimartin Just confirmed this bug.
```
fmt.Fprint("some text here\r\n")
```
does not print on the screen with the current build.

To make the text visible, you must do a 
```
line := strings.Replace(string(data), "\r", "", -1)
```
