### ISSUE TITLE
Unable to get View after using SetLayout

### ISSUE THREAD

**Issue by t94j0** [jroimartin/gocui#52]
In my layout function, I am creating the view messages_box using `g.SetView("messages_box", 0, 0, maxX, maxY-5)`. After using g.SetLayout(layout), I try to call `messageView, err := g.View("messages_box")`, but I keep getting "unknown view."

**Comment by jroimartin** [comment]
Can you send a small snippet to reproduce the error? Also, have you taken a look at the `_examples` folder?

**Comment by jroimartin** [comment]
Also, where are you calling g.View from? As you can see in the [documentation](https://godoc.org/github.com/jroimartin/gocui):

```
IMPORTANT: Views can only be created, destroyed or updated in three ways: from layout functions, from keybinding callbacks or via *Gui.Execute().
```

**Comment by t94j0** [comment]
I am now using Gui.Execute() and it is working. My bad for not reading the docs well enough.
