### ISSUE TITLE
cygwin on Microsoft Windows - gocui no views are shown

### ISSUE THREAD

**Issue by kkellner** [jroimartin/gocui#64]
Running gocui on Microsoft Windows with a cygwin shell, no views are shown.   E.g., running _example/hello.go results in no output.  Looks like it hangs, but ctrl-c does exit the app.

**Comment by jroimartin** [comment]
gocui uses [termbox-go](https://github.com/nsf/termbox-go) under the hood. As a result, it has native windows support and should just work with both cmd.exe and powershell. Have you tried it?

On the other hand, looking for "cygwin" in the termbox-go repo I found the following issue:
* https://github.com/nsf/termbox-go/issues/66

**Comment by kkellner** [comment]
cmd.exe works fine.  It does look like nsf/termbox-go#66 is the issue I'm running into.  Unfortunate this doesn't work.   A not-ideal workaround is to run this in cygwin terminal: "cmd.exe /c mygoprogram.exe".   This launches a new terminal windows running "cmd.exe" where the application works.   Just not a great end-user experience.
