### ISSUE TITLE
assignment count mismatch: 2 = 1

### ISSUE THREAD

**Issue by cocodrino** [jroimartin/gocui#71]
Hi, I'm receiving this error with every updated example

for instance
```shell

go run demo.go                                                                                                       master 
# command-line-arguments
./demo.go:19: assignment count mismatch: 2 = 1
./demo.go:22: assignment count mismatch: 2 = 1
./demo.go:67: assignment count mismatch: 2 = 1
./demo.go:78: assignment count mismatch: 2 = 1
./demo.go:186: assignment count mismatch: 2 = 1
./demo.go:194: assignment count mismatch: 2 = 1


```

this only happens with the latest gocui, samples in prior commits show ok

```shell
 all these samples run ok

bufs.go    demo.go     goroutine.go  layout.go			mask.go   ontop.go    stdin.go	wrap.go
colors.go  dynamic.go  hello.go      Mark.Twain-Tom.Sawyer.txt	mouse.go  overlap.go  title.go


```

do you know what could be the issue
thanks!!

**Comment by jroimartin** [comment]
I've just tested it and it's working fine. Are you mixing different versions between demos and gocui?

**Comment by cocodrino** [comment]
nope..I've removed the old gocui, then install the new one and clone the repo, after check than it doesnt work I tried the examples in the old repo and they work ok...I'll check this more deep tomorrow, I was really interested in check the new examples :crying_cat_face:

**Comment by jroimartin** [comment]
Try with:

```
$ go get -u github.com/jroimartin/gocui
$ cd $GOPATH/src/github.com/jroimartin/gocui/_examples && go run demo.go
```

**Comment by cocodrino** [comment]
Hi...after update the go version and the package I was able to run the samples..thank so much it looks great
