### ISSUE TITLE
256 colors

### ISSUE THREAD

**Issue by mephux** [jroimartin/gocui#72]
Any reason why  using this shouldn't work? https://github.com/aybabtme/rgbterm

**Comment by jroimartin** [comment]
Right now gocui uses termbox with `OutputNormal` (8 colors) because it should work in all terminals. For instance, in the case of windows, this is the only valid mode:

https://github.com/nsf/termbox-go/blob/b6acae516ace002cb8105a89024544a1480655a5/api_windows.go#L225-L231

Maybe, we can keep `OutputNormal` as default and provide a new option to set the mode to 256 colors.

For more information:
https://godoc.org/github.com/nsf/termbox-go#SetOutputMode

**Comment by mephux** [comment]
@jroimartin roger, makes sense. I'll start playing around with SetOutputMode

**Comment by mephux** [comment]
@Jameskmonger so I had more time to look into this - looks like we would need to change all the SetCell calls for 256 support but that's connected to a lot of other calls.

Before I start to try and add support for this, do you have any recommendations on how you want that to work? Would hate to have to use a fork and would rather produce something that can be merged into this project.

**Comment by jroimartin** [comment]
@mephux why would you need to change all the calls to `SetCell()`?

I could not look into it, but I feel that it's more related to `*escapeInterpreter.parseOne()`. You should handle 256-colors ESC sequences, so the cell colors are set accordingly. Also, it shouldn't be possible to change between output modes during the execution.

**Comment by mephux** [comment]
@jroimartin was basing that off the comments here https://github.com/nsf/termbox-go/blob/b6acae516ace002cb8105a89024544a1480655a5/api.go#L409-L419

**Comment by jroimartin** [comment]
Yes, but it's all about setting the correct `curFgColor`/`curBgColor` values in `*escapeInterpreter.parseOne()`, right?

So, if you implement parsing for 256-colors ESC sequences, `SetCell` should be called with the right new colors.

```go
termbox.SetCell(v.x0+x+1, v.y0+y+1, ch, termbox.Attribute(fgColor), termbox.Attribute(bgColor))
```

At least, that would be my first approach, but I might be missing something :)

**Comment by jroimartin** [comment]
BTW thanks a lot for your help!

**Comment by mephux** [comment]
@jroimartin no worries and you're correct. I'll get it done. :)

**Comment by mephux** [comment]
@Jameskmonger ok, pushed an atrocious prototype for 256 support https://github.com/mephux/gocui

 * Option to set OutputMode: https://github.com/mephux/gocui/blob/master/gui.go#L77-L86
 * Escape logic: https://github.com/mephux/gocui/blob/master/escape.go#L144-L242

I also created a branch of my IRC client that is using it: https://github.com/mephux/komanda-cli/tree/256


A few issues I ran into was grayscale text (none will work) - I guess my escape logic is just all fucked up..The gocui changes I made were added to the vendor dir with that branch if you want to look at it.

![screenshot](https://cloud.githubusercontent.com/assets/22273/20032898/627ad26e-a36a-11e6-95c7-531b1c7cb805.png)

**Comment by mephux** [comment]
Another note: https://github.com/mephux/komanda-cli/blob/256/komanda/color/color.go#L27
Should be light grey - the ouput is correct.. 

```logs :: util.go:263: (string) (len=23) "\x1b[38;5;124m03:20\x1b[0;00m"```

but shows a pinkish.. haha

**Comment by jroimartin** [comment]
Awesome! Can you open a PR? It'll be easier for code reviewing and making changes.

**Comment by mephux** [comment]
@jroimartin done

**Comment by jroimartin** [comment]
Great. I referenced this issue from the PR, so I'm closing this issue and we can continue the discussion there.
