### ISSUE TITLE
Is there any plans to implement something like Turbo Vision?

### ISSUE THREAD

**Issue by rgl** [jroimartin/gocui#73]
Is there any plans to implement something along the lines of [Turbo Vision](https://en.wikipedia.org/wiki/Turbo_Vision) or [Free Vision](http://wiki.freepascal.org/Free_Vision)? That is, having windows and widgets?

You can see images about its widgets at the [google images](https://www.google.com/search?q=turbo+vision) (switch to the images tab).

**Comment by jroimartin** [comment]
Based on the images, a user should be able to implement similar interfaces combining Views, Keybindings and Managers to create widgets and layouts than can be reused. I want to keep gocui really simple, exposing enough functionalities to allow building more complex stuff on top of it.
