### ISSUE TITLE
Rename *Gui.Execute() to *Gui.Do()

### ISSUE THREAD

**Issue by jroimartin** [jroimartin/gocui#79]
Rename `*Gui.Execute()` to `*Gui.Do()` and update documentation accordingly.

Relates to #77

**Comment by frizinak** [comment]
Can I also note this method does not guarantee the order in which userEvents are handled. You currently spawn a go routine to prevent the call from potentially blocking thus the channel push only occurs when the scheduler feels like it (and not in the order of the `gui.Execute` calls necessarily).

I would suggest making this call fully synchronous, not only waiting for the channel push to succeed but also for the userEvent.f to return. If the user doesn't want to wait he's free to `go gui.Execute`. Making it a more intuitive and still thread-safe method.

My current workaround (as this does occur very often) is to do exactly that. Lock a mutex before `.Execute` and release at the end of the userEvent.f implementation.

**Comment by jroimartin** [comment]
Having both an async and sync methods could be useful. I'll take it into account. Thanks!

**Comment by jpeeler** [comment]
I was surprised to see that the events were not FIFO. If a sync method or flag was available, that would be nice.

**Comment by libeclipse** [comment]
I think .Update would be a better name for this. The two suggestions don't really get across what the function is actually for imo.

**Comment by jroimartin** [comment]
Renamed to `*Gui.Update()` via 6564cfcacb01db61e3a4e983405a598db3e91982.
