### ISSUE TITLE
Extra character outputted when typing

### ISSUE THREAD

**Issue by libeclipse** [jroimartin/gocui#80]
This (bug?) isn't immediately obvious, but it pops its head up on Windows especially.

When typing, there's an extra character that is outputted where your cursor is. You can make it more obvious by activating the mask in `_examples/mask.go` and typing. Pressing the delete key removes this extra character. In Linux it's invisible but in windows it shows up, I'm thinking maybe it's an ANSI escape code?

Copying it from my Linux terminal just tells me it's an extra `U+0020 : SPACE [SP]`, but that wouldn't explain why it shows up as a visible (albeit fucked up) character in Windows. Either way, it shouldn't be there.

**Comment by jroimartin** [comment]
Duplicates: #69 
Relates to: #60

**Comment by libeclipse** [comment]
Are you sure that it's a `NULL` at the end of the line? Like I said, copying it seems to show that it's a `\x20` (SPACE).

**Comment by jroimartin** [comment]
Yes, it should. I'm referring to the internal representation.
