### ISSUE TITLE
Buffer isn't fully cleared when clear() is called and cursor isn't reset.

### ISSUE THREAD

**Issue by libeclipse** [jroimartin/gocui#81]
This should really be two different issues but they're closely related so I'll group them together here.

Say there's an input box. There's a key binding for `KeyEnter`, and when it is triggered, we grab the buffer with `v.Buffer()`, handle it, then do the following to clear and reset:

```
v.SetCursor(0, 0)
v.Clear()
```

However, the cursor position seems to only reset to the top of what's in view and the whitespace remains.

So for example if I use the arrow keys to move the cursor down a few lines and then type something and press enter, when we handle and reset the buffer, all subsequent inputs have whitespace at the beginning and the arrow keys have to be used to move the cursor back to the origin.

**Comment by jroimartin** [comment]
Take into account that the position is governed by two functions:
* `*View.SetCursor()`: https://godoc.org/github.com/jroimartin/gocui#View.SetCursor
* `*View.SetOrigin()`: https://godoc.org/github.com/jroimartin/gocui#View.SetOrigin

**Comment by libeclipse** [comment]
Ah I see `SetCursor()` is behaving as expected. Am I right in thinking that - to move the cursor to the original origin place - I'd do both `SetOrigin(0, 0)` and `SetCursor(0, 0)`?

**Comment by jroimartin** [comment]
Exactly, you are right.

You can think of a View as a "window" over a buffer, so `SetCursor()` sets the position on the cursor within this window and `SetOrigin()` sets the position of the window with respect to the buffer.

**Comment by jroimartin** [comment]
Should we close this issue?

**Comment by libeclipse** [comment]
I'm not at home right now, but when I am, I'll test this and then close it.

**Comment by libeclipse** [comment]
Nice, that seems to have fixed it.
