### ISSUE TITLE
Disabling arrow keys for empty lines.

### ISSUE THREAD

**Issue by awnumar** [jroimartin/gocui#82]
When using a text editor, it's customary that using the `down` or `right` arrow keys have no effect when we're at the end of the text and there's no more characters after the cursor. The `enter` key is then used to insert a new line.

In an input box created with `v.Editable = true`, the cursor keys can be used indefinitely to create newlines (see `_examples/mask.go`). Since we're still pre-`v1.0.0`, I think this is a safe change to make.

**Comment by jroimartin** [comment]
This will be handled by the new edition mode. We'll close this issue after confirming that the new edition mode effectively fixes this.

Relates to: #60

**Comment by libeclipse** [comment]
Is there any update to `v0.4`?

**Comment by jroimartin** [comment]
I've been working on other projects during the last months, but I plan to resume gocui's development soon. Sorry for this inactivity period.

**Comment by libeclipse** [comment]
@jroimartin Not to be pushy or anything, but is there an ETA? I have a few projects that are on hold until this is fixed.

**Comment by oakes** [comment]
Possibly related, but I noticed (at least in the OS X terminal app) scrolling causes ASCII codes like `<64;72;17M` to appear. Perhaps there is a way to intercept text before it gets to the buffer, so we can prevent that from appearing?

**Comment by jroimartin** [comment]
@oakes related: https://github.com/jroimartin/gocui/issues/35

**Comment by oakes** [comment]
@jroimartin Interesting, thanks. Is there a way to just disable mouse scrolling altogether?

**Comment by jroimartin** [comment]
Fixed via 75a7ad275059b14eb43b704717ef23d42b2fea4d. Could you check? :)

**Comment by jroimartin** [comment]
BTW you can use `_examples/bufs.go` to test it easier.
