### ISSUE TITLE
Correct concurrent use of stdin : user input field

### ISSUE THREAD

**Issue by Spriithy** [jroimartin/gocui#83]
Hey there, I'm totally new to `gocui` / `term-box` etc.
I am trying to make a simple frame in which on can type text in an input field and when hitting enter, the field is cleared, and text appended to another view.

However, when using the `/_examples/stdin.go` method, the program just freezes before even displaying the frames.

How should I go about it ?

**Comment by libeclipse** [comment]
You can have a key binding to KeyEnter that handles the Buffer and resets everything. You can knit together a solution using the different examples in `_examples`.

**Comment by Spriithy** [comment]
Is `stdin` still being updated as I type in a view ? If yes, that's fairly easy

**Comment by libeclipse** [comment]
When you type in a view, the data is stored in an internal buffer that can be accessed with `v.Buffer()`, and cleared with `v.Clear()`. See the docs for details.

**Comment by Spriithy** [comment]
Oh and, `g.SetCurrentView("...")` seems not to give the stdin focus to the given frame ...

**Comment by libeclipse** [comment]
I'm not sure what you mean. Could you elaborate on what you're trying to do exactly and what part of it isn't working as expected?

**Comment by Spriithy** [comment]
Sure, there I have a small snippet that sets the focus on the`in` view.
```go
g.SetCurrentView("in")

if err := g.MainLoop(); err != nil && err != gocui.ErrQuit {
	panic(err)
}
```
In my keybind initializing phase I have (when pressing `Return`) this :
```go
// removed error handling for conciseness
in_view, err := g.View("in")
out_view, err := g.View("out")
out.Println(in_view.Buffer())
in_v.Clear()
```

which redirects the content of the `in_view` buffer to the `out` view. However, the only content I can manage to have printed correctly is the initial content of `in_view`. That is to say, that when I type anything, the content is not being reported to `in` at all (checked with raw println(.) as well).

**Comment by libeclipse** [comment]
Correct me if I'm wrong @jroimartin 

I don't think views have a Println() method. The correct way to print to a view is to call `fmt.Fprintln(v, data)`.

Also, the `g.SetCurrentView()` should be called after the `g.SetView()` declaration.

**Comment by Spriithy** [comment]
I know they don't have the `Println` method :) I implemented it in my custom view type

**Comment by Spriithy** [comment]
Well, even with everything setup as expected and asked by the doc, the production is not really what expected ... Are you sure the `stdin` content is redirected to the `.Buffer()` method of the view ? @libeclipse

**Comment by libeclipse** [comment]
Anything that is typed into an editable view ends up in the Buffer.

**Comment by jroimartin** [comment]
First things first,

`_examples/stdin.go` reads from stdin and dumps the read data in hex to a view. It can be used as follows:

```
$ cat /bin/ls | go run _examples/stdin.go 
```

Now, I think you don't want to read from stdin but from other view. So, you need something like this:

https://gist.github.com/jroimartin/364810d993fbf7dca8f79fc45dd9e5fa

Is that right?

**Comment by jroimartin** [comment]
BTW the correct approach here would be to create an input widget using the Manager interface and so on. So, take this just as a quick example :)

**Comment by Spriithy** [comment]
Hey, thanks for the reply! 
Well, that's clearly what I wanted to do! haha I just couldn't get my view to be editable 
Thanks for the work done so far and the help!

**Comment by jroimartin** [comment]
Great! 👍
