### ISSUE TITLE
Scrolling programmatically?

### ISSUE THREAD

**Issue by libeclipse** [jroimartin/gocui#84]
Is it possible to scroll programmatically, say with the arrow keys?

For example, say I have a view that has `v.AutoScroll = true`. Data is continuously printed to this view and so of course the data goes out of view after a while and new data replaces it.

Is it possible to bind `KeyArrowUp` and `KeyArrowDown` to scroll the view `n` lines up and down, respectively?

**Comment by jroimartin** [comment]
Yes, you can use `*View.SetOrigin()` to implement scrolling. For instance:

https://github.com/jroimartin/gocui/blob/master/_examples/stdin.go#L100-L109

**Comment by libeclipse** [comment]
I see that `v.AutoScroll` is set to false. Is this a temporary change? Ideally I'd like `v.AutoScroll` to be true when the view is at the bottom.

**Comment by jroimartin** [comment]
You could use `*View.Origin()` and `*View.Cursor()` to calculate the y-position of the cursor in the view, then you can compare it with the number of lines in `*View.ViewBuffer()` to check if the view is at the bottom.

**Comment by libeclipse** [comment]
Thanks for the advice. Here's some reference code for anyone else who might run into the same problem:

```
func scroll(dy int) {
        // Grab the view that we want to scroll.
	v, _ := gui.View("the_view_we_wish_to_scroll")

        // Get the size and position of the view.
	_, y := v.Size()
	ox, oy := v.Origin()

        // If we're at the bottom...
	if oy+dy > strings.Count(v.ViewBuffer(), "\n")-y {
                // Set autoscroll to normal again.
		v.Autoscroll = true
	} else {
                // Set autoscroll to false and scroll.
		v.Autoscroll = false
		v.SetOrigin(ox, oy+dy)
	}
}
```
