### ISSUE TITLE
redraw on ^L

### ISSUE THREAD

**Issue by alicebob** [jroimartin/gocui#88]
Hi!

sometimes I mess up the screen with debug `print()`s, so I would like to bind ^L to force-redraw the whole screen when that happens. I can't find the redraw-everything function which, I think, is `Sync()` in termbox. Did I overlook the function? Or is it not available? Can I call termbox' `Sync()` somehow?

Thanks!

**Comment by jroimartin** [comment]
Hi!

First of all, sorry for my late response! Right now gocui does not exposes any method to call `termbox.Sync()` and I'm not sure if it should be added to the API. However, although **it's not recommended**, you can do something like this for your tests:

```go
if err := g.SetKeybinding("", gocui.KeyCtrlL, gocui.ModNone,
        func(g *gocui.Gui, v *gocui.View) error {
                return termbox.Sync()
        }); err != nil {
        // TODO: handle the error
}
```

**Comment by bwmarrin** [comment]
@jroimartin 

Is this still the only solution.  There's been a couple people needing this in the past, and I'm needing it as well.  I'm using the above "hack" but exposing a Redraw() or similar func in the GOCUI library would be nice.  

What's the main concern for not wanting this in the library itself?
