### ISSUE TITLE
undefined gocui.quit gocui.ModNone

### ISSUE THREAD

**Issue by owllie90** [jroimartin/gocui#89]
Hi, 

I am installing sumoshell. But i have encountered the below errors:

undefined: gocui.Quit
undefined: gocui.ModNone

Kindly advise.

**Comment by jroimartin** [comment]
Hi,

Sorry for the late response. These errors have to do with the last changes introduced in gocui which required to modify its API. More info at:

https://github.com/jroimartin/gocui/issues/77#issuecomment-260179983

Sumoshell should be updated accordingly and they should also start using vendoring.

Thanks for reporting it!
