### ISSUE TITLE
_example code does not run

### ISSUE THREAD

**Issue by carlca** [jroimartin/gocui#95]
Hello, I've installed the code using ```go get github.com/jroimartin/gocui``` and tried to run several of the items in _examples. None of them run. Instead the go runtime just hangs with a blank line until I press Ctrl-C. I don't believe I've missed anything and I am waiting maybe 30 seconds before giving up. What am I doing wrong?

I'm running Go 1.7.4 on Windows 10 Pro 64 bit Insider Preview build 15014
I'm using Git Bash to launch the go examples. (i'll try some other ways and post back)

UPDATE: It seems that the library does produce any visible output with Powershell or Git Bash. The only way I have of getting it to work is using CMD. I have ran all the example files successfully except for stdin.go which just drew a blank screen. I'm guessing that you are writing "directly" to screen memory for performance reasons so I understand why this is happening. 

Could you maybe allow a choice of screen write methods to allow the use of Git Bash as this would presumably be your target market.

Anyhow it's a nice piece of work and I shall investigate it more closely in the next few days.

**Comment by jroimartin** [comment]
gocui uses [termbox-go](https://github.com/nsf/termbox-go) under the hood, which is the package used to interact with the terminal. So, gocui is compatible with those terminals supported by termbox.

**Comment by carlca** [comment]
Its Ok, I've got working with CMD. So everything is good! Thanks.
